version: "3.8"

services:
  redis:
    image: redis:alpine

  app:
    build: .
    container_name: khaja_khaja
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src/app/khaja_khaja
    ports:
      - "8000:8000"
    depends_on:
      - redis

  celery:
    restart: always
    build: .
    volumes:
      - .:/usr/src/app/khaja_khaja
    command: celery -A khaja_khaja worker -l INFO
    depends_on:
      - app
      - redis