version: "3.8"

services:
  redis:
    image: redis:alpine

  app:
    container_name: khaja_khaja_prod
    build: .
    command: gunicorn khaja_khaja.wsgi:application --bind 0.0.0.0:8000
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - db

  db:
    image: postgres:13.0-alpine
    volumes:
      - db_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER="${POSTGRES_USER}"
      - POSTGRES_PASSWORD="${POSTGRES_PASSWORD}"
      - POSTGRES_DB="${POSTGRES_DB}"

  celery:
    restart: always
    build: .
    volumes:
      - .:/usr/src/app/khaja_khaja
    command: celery -A khaja_khaja worker -l INFO
    depends_on:
      - app
      - redis
      - db

volumes:
  db_data: