# Generated by Django 3.2.5 on 2021-09-29 10:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('R', 'Read'), ('U', 'Unread')], default='U', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('shipping_address', models.CharField(blank=True, max_length=100, null=True)),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cart.orderitem')),
            ],
        ),
    ]
