# Generated by Django 3.2.5 on 2021-08-18 05:43

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2021, 8, 18, 5, 43, 59, 431914, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
