# Generated by Django 3.2.5 on 2021-07-27 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('logo', models.ImageField(blank=True, upload_to='restaurant/logo/')),
                ('license_number', models.CharField(max_length=50)),
                ('seconday_phone_number', models.CharField(blank=True, max_length=50)),
            ],
        ),
    ]
