# Generated by Django 3.2.5 on 2021-08-19 05:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='restaurant',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='restaurant', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fooditems',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category', to='restaurant.category'),
        ),
        migrations.AddField(
            model_name='fooditems',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restaurant_item', to='restaurant.restaurant'),
        ),
        migrations.AddField(
            model_name='fooditems',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='tags', to='restaurant.Tags'),
        ),
        migrations.AddField(
            model_name='discount',
            name='food_item',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='discount_food_item', to='restaurant.fooditems'),
        ),
        migrations.AlterUniqueTogether(
            name='fooditems',
            unique_together={('restaurant', 'name')},
        ),
    ]
