# Generated by Django 3.2.5 on 2021-08-09 05:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('restaurant', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='restaurant',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='restaurant', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='menu',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restaurant_menu', to='restaurant.restaurant'),
        ),
        migrations.AddField(
            model_name='fooditems',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category', to='restaurant.category'),
        ),
        migrations.AddField(
            model_name='fooditems',
            name='menu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu', to='restaurant.menu'),
        ),
        migrations.AddField(
            model_name='fooditems',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='tags', to='restaurant.Tags'),
        ),
        migrations.AlterUniqueTogether(
            name='menu',
            unique_together={('restaurant', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='fooditems',
            unique_together={('menu', 'name')},
        ),
    ]
