# Generated by Django 3.2.5 on 2021-08-19 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_status', models.CharField(blank=True, choices=[('order_created', 'Order Created'), ('processing', 'Processing'), ('delivered', 'Delivered')], max_length=50, null=True)),
                ('shipping_address', models.CharField(max_length=100)),
                ('total_cost', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('cost', models.PositiveIntegerField(default=0)),
                ('ordered', models.BooleanField(default=False)),
            ],
        ),
    ]
