name: Test docker build workflow
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker-compose up --build

    - name: Make migrations
      run: docker exec -it khaja_khaja python manage.py migrate

    - name: Make migrations
      run: docker exec -it khaja_khaja python manage.py test

    - name: Stop Containers
      run: docker-compose down